[package]
name = "pyo3-test"
version = "0.1.0"
authors = ["MURAKI Taichi <muraki.taichi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
